### ISSUE TITLE
Hi, i am facing tool tab it is not showing full screen 

### ISSUE THREAD

**Issue by besthani786** [hellovimo/uvm_testbench_gen#3]

**Comment by besthani786** [comment]
![MicrosoftTeams-image (10)](https://github.com/hellovimo/uvm_testbench_gen/assets/113415215/55794561-efc6-430a-a908-518291c652f6)

**Comment by besthani786** [comment]
i am facing tool tab issue, i cant scroll downside to add signal and execute buttons

**Comment by hellovimo** [comment]
Hello @besthani786 

1. the snapshot which you posted above, is it the full window ?
2. I think the resolution of you machine is different which is making the tool go out of the view. 

Can you try changing the linux machine display settings n give a try ?

**Comment by besthani786** [comment]
Hi,

Full screen tool tab issue is resolved. We fixed it.
Now, we are facing issue in DONE INTERFACE CONFIG button is not working, please check it given below snapshot.

***@***.***
Thanks,
Esthani

**Comment by hellovimo** [comment]
Hello @besthani786  Can you please upload the snapshot ? I don't see any new snapshot.. The only one which I see the the previous one.

**Comment by besthani786** [comment]
Hi Vignesh,

We want to audit the tool Py_UVM_Gen. We are facing the following issue.

  *   DONE INTERFACE BUTTON is not working.
  *   We are not able to generate the interface.

[cid:75114032-aadd-4dfa-ae58-daefe015841b]

Kindly help us at the earliest.

Thanks,
Khausik
________________________________
From: Esthani H ***@***.***>
Sent: Thursday, September 7, 2023 12:31 PM
To: hellovimo/uvm_testbench_gen ***@***.***>; hellovimo/uvm_testbench_gen ***@***.***>
Cc: Mention ***@***.***>; Marmik Bhupendrakumar Soni ***@***.***>; Khausik Seenivasan ***@***.***>; Manicka Vinodhini ***@***.***>
Subject: RE: [hellovimo/uvm_testbench_gen] Hi, i am facing tool tab it is not showing full screen (Issue #3)


Hi,



Full screen tool tab issue is resolved. We fixed it.

Now, we are facing issue in DONE INTERFACE CONFIG button is not working, please check it given below snapshot.



***@***.***

Thanks,

Esthani

**Comment by hellovimo** [comment]
Hello @besthani786 My bad was away a bit. You still facing this issue or it got resolved with the clean/new try ? Please let me know. Thanks.
